### ISSUE TITLE
Issue rendering new Emojis from Unicode 13.0

### ISSUE THREAD

**Issue by tonnoz** [appfigures/react-easy-emoji#10]
Hello I am facing some issue while rendering any of the new emojis from the [Unicode 13.0 specs](https://blog.emojipedia.org/twemoji-13-0-emoji-changelog/) for example:
🥲 (\u1F972)
🥸 (\u1F978)
🤌 (\u1F90C)

see screenshot:

![image](https://user-images.githubusercontent.com/2478866/82200669-99a48580-98ff-11ea-95fd-0e602c10698f.png)

I am passing the raw char to the `emoji` function. All the emojis from Unicode 12 or lower are ok.

**Comment by tonnoz** [comment]
[UPDATE] I solved for now using [twemoji](https://github.com/twitter/twemoji) lib but I would prefer react-easy-emoji because is more lightweight.

**Comment by lefnire** [comment]
would using v/latest in twemoji cdn work? `emoji(input, {baseUrl: 'https://twemoji.maxcdn.com/v/latest/'})`

**Comment by oztune** [comment]
I'm happy to say this has been fixed in v1.5.0
