### ISSUE TITLE
Maxcdn has shut down, emoji images not loading

### ISSUE THREAD

**Issue by tiotdev** [appfigures/react-easy-emoji#23]
See here: https://github.com/twitter/twemoji/issues/580

Switching to an alternate CDN should solve this

**Comment by tiotdev** [comment]
Solved it for my project by self-hosting and using the custom baseUrl parameter, but the default should be changed to a working cdn

**Comment by oztune** [comment]
Thanks for reporting this! We just updated the default to point to `cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2` and released a new build on npm.
