### ISSUE TITLE
 The package react@15.6.2 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by susmitha01** [appfigures/react-easy-emoji#6]
I'm trying to install

> 
npm install --save react-easy-emoji

But its throwing an error ' The package react@15.6.2 does not satisfy its siblings peerDependencies requirements '

**Comment by oztune** [comment]
@susmitha01 That's odd, would you mind sharing the entire output of the error?
As you can see in https://github.com/appfigures/react-easy-emoji/blob/master/package.json#L28 we support any 15.x version.

**Comment by susmitha01** [comment]
![screen shot 2018-08-07 at 9 27 45 am](https://user-images.githubusercontent.com/20550475/43753627-550d63c8-9a24-11e8-8bc2-a0fc308f628f.png)

As, i uploaded the above image , please tell me what is the issue

**Comment by oztune** [comment]
It looks like react-emojione requires react^16 so maybe that’s the source of your error.
